---
apiVersion: v1
kind: ConfigMap
metadata:
  name: baasmanager
  namespace: default
  labels:
    app.kubernetes.io/name: baasmanager
    app.kubernetes.io/instance: 1.17.9
data:
  baas.conf: |-
    # baas-gateway地址
    upstream baasapi {
        server localhost:6991;
    }
    # HTTP server
    server {
        listen       8080;
        server_name  baasadmin;

        location /nginx_status {
                stub_status on;
                access_log off;
        }
        location /api/{
            proxy_pass  http://baasapi/api/;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header Host $host;

        }
        location /dev-api/{
            proxy_pass  http://baasapi/api/;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header Host $host;

        }
        location /stage-api/{
            proxy_pass  http://baasapi/api/;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header Host $host;

        }

        location / {
            root   /usr/share/nginx/baas;
            index  index.html index.htm;
        }

        location ~ ^/favicon\.ico$ {
            root   baas;
        }
            
    }

  gwconfig.yaml: |-
    # gateway引擎端口
    BaasGatewayPort: 6991
    # fabric引擎地址
    BaasFabricEngine: http://localhost:4991
    # db配置
    BaasGatewayDbconfig: /etc/gateway/dbconfig.yaml
  dbconfig.yaml: |-
    xorm:
      drivename: mysql
      ip: 118.89.37.37
      port: 3306
      database: baas_api
      user: root
      password: 123456
      #是否显示sql语句
      showsql: true
      #连接池中idle态链接最大个数
      maxidle: 10
      #连接池最大打开连接数
      maxopen: 5
  keconfig.yaml: |-
    # k8s引擎端口
    BaasKubeEnginePort: 5991
    # k8s集群master config
    BaasKubeMasterConfig: /etc/k8sconfig/config
  k8sconfig: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EVXhNakF3TlRRMU5Gb1hEVE13TURVeE1EQXdOVFExTkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnRBClhlYWgvSHdGSkhXeENLdVNEcDBtN21IRGZBWXkzUSszWE5MbnRVcW1HVTE4a0MvV3V1aVJQTmxsY0cwTDBtQnQKQmVEc0Jnb09IV2EwY2I4aWZYNGhWTDVYbnpFL0tvVDN4ZzJxWVdlUHpKQUtZYzdEWTF2MzJaYlErbk11VmtkSAp2cEcvQm1vK09VTjFVYWM2a2tKM2IzcFJyVXNvN1o5RnR2dC9vSERKVVNvS1lrck42UktKTGNjMmhyaWl5M0l0CmdQd05UeVBsYTdaeGRIcUdPMzY1OHd4M1NmcDErMG5lTE45STI4N29EOXhYZElLRjBKSjBSYVpsaXp0bzVLQ08KUkdIaDJ2a0tMYjhTRDR6OG9MUHFVY28zYlZKS0FyRFNrSURMQSt6V1NBcHVaQVgreU9zM00yZHBJRWpWSXBCdgpBcy9sOHp4TUVDeENKMnVRQ2QwQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFJNldXejdEVGsrTDZlNGxJV24vaEorYU1oUGcKelk0K3N1MndaS3dUZWEza04zRzNQWm9GYys4U09Gb1o3cG5abzMxOVhlQmJlYTJsM2F5VHQ4NENKUHNyUllrRgpaaGlyK2JqcGZZK2d5S2h0YjFuYW14ZFBUT0YvdnI4UFNmZ2JHOFE5alY2MzRLK1VmanRMTjY1QnBqcmJSd2tTClBhai8rQnVZVGFoVjRNL0kwNFU1YXdvWlpydks3bVZ4TXY0VjlvN3lnNG1UMkRnOVR6R21FanNFR1pncjU3ZDEKTG1wSk5qK2MzY3EzSFpVTVVGK2t2dC9UMTZkamZpS2w5cWlFV0VONTgyMlptcGtlUWR5TFgrdCtWUlVHWi9yQQprOFR0L3lKU1lLc1VscEdTeGRSR2FrMTI1d2FubVBGWDhQbHZUZm5vcUlEZXh6dzBOc0NIYmJFNDdobz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        server: https://kubernetes.docker.internal:6443
      name: docker-desktop
    - cluster:
        certificate-authority: /etc/k8sconfig/ca-hou02-mycluster.pem
        server: https://c6.hou02.containers.cloud.ibm.com:30948
      name: mycluster/bqrvi4bd01rn5kmc0flg
    contexts:
    - context:
        cluster: docker-desktop
        user: docker-desktop
      name: docker-for-desktop
    - context:
        cluster: mycluster/bqrvi4bd01rn5kmc0flg
        namespace: default
        user: luweb@foxmail.com/cf1b8d269da816c6bf803b6591761eca
      name: mycluster/bqrvi4bd01rn5kmc0flg
    current-context: docker-for-desktop
    # current-context: mycluster/bqrvi4bd01rn5kmc0flg
    kind: Config
    preferences: {}
    users:
    - name: docker-desktop
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQWR5Z0F3SUJBZ0lJS1I1d2ZMWUNRMm93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBMU1USXdNRFUwTlRSYUZ3MHlNVEExTVRjd05qVTRORFZhTURZeApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sc3dHUVlEVlFRREV4SmtiMk5yWlhJdFptOXlMV1JsCmMydDBiM0F3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3hFa3dMYS9TVHcwaUIKZnBtY0VvU1Y1My85QUVzb1RxZzAwN3VwY0ZoU0FOeUh6QnNGV0xyTEhmYzd0aHZGKzYwY2I2RUZDbzJ5ZkhKLwovQzhmQ2RkMHFxMmkwdjd6SzBHbEs2S1RNWFdvZHlWOHpUZG5MN0s2bmJXK0IzQXdicTFXeDljN0VwaHZ4YkVqClBhZDcyYWRFZkRNcnF2a2UyYkw0OHFqN1UrR01zeXNhUEtaTnJCcHJVTTcrd2I2a3V0eE5GKzFYdEpQMUEwYjEKRzJCdXVhR0pJNzVTWnZORWZKSWZ4c1ZuVGN5U1hUbG5xU0pEZE93QVFZKzZzc3JPVDNNRTg0SFMvRWpqNGsxdAphMS85b3dlZTRSL3h2OXI1akFRbjdKWU5mRzdiMWZHOGhZNVg5OXR6azNQSzJnS1c1QjVyMzNsNEJTa2VpNlF5Cmt3Ymo1blVKQWdNQkFBR2pKekFsTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFmbjRCWmowazAvbHpmeVJ0Rk5QSmo0RGFpeWxtdjlHYQpvN1ZTeGVtb0RDUGJOMDRTRGY4TFFJYTNXSmJSVjQxdVYxeWFrTjhaeUFtckQyK1RVUHQ1WkxTSmo1N24yVzdTClpSV3BkcitvaDV0RkZPSEJ1eS9zVU9kSFZ5MFFiWE9hZVl3QUFTc0xmVytRcVhEeGFQeXhKWGdrSzVpZ3ZwUC8KNWRRTndMUFdMejl5Zks3QzZlT3hIUG0yM0lNQkVhanZiWWpudlJYZFNOV0FTUkYrc3lNeERDTFAvRmttcVRPNQpHdFI2SzZaNmx4eFQ1QUxKSVFBcTJBaVNXUVpQdEhaRFplckpTVGVrcUNXYkRJZVFPcS96YnZrM2xPakg0MzFxCmY4WDczaWhFMXRaVElSZElSaFVxMkZVcXJoRHROWTh5WjNJN1JvTGVWZEQyWjdSZmNDVlFtUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBc1JKTUMydjBrOE5JZ1g2Wm5CS0VsZWQvL1FCTEtFNm9OTk83cVhCWVVnRGNoOHdiCkJWaTZ5eDMzTzdZYnhmdXRIRytoQlFxTnNueHlmL3d2SHduWGRLcXRvdEwrOHl0QnBTdWlrekYxcUhjbGZNMDMKWnkreXVwMjF2Z2R3TUc2dFZzZlhPeEtZYjhXeEl6Mm5lOW1uUkh3eks2cjVIdG15K1BLbysxUGhqTE1yR2p5bQpUYXdhYTFETy9zRytwTHJjVFJmdFY3U1Q5UU5HOVJ0Z2JybWhpU08rVW1ielJIeVNIOGJGWjAzTWtsMDVaNmtpClEzVHNBRUdQdXJMS3prOXpCUE9CMHZ4STQrSk5iV3RmL2FNSG51RWY4Yi9hK1l3RUoreVdEWHh1MjlYeHZJV08KVi9mYmM1Tnp5dG9DbHVRZWE5OTVlQVVwSG91a01wTUc0K1oxQ1FJREFRQUJBb0lCQUhCc2w0K2c2Vlp2NUxjagpORkJkaVlUTHlQMVBsR2h4R0djQ0QrSlNqQ0QwbnhBeFRPNm1HV01oRVhuOTg4Qk9QT2tURHY3dVptenVpcHdyCjk1Y1RYcEthVTBoUUFzTk5zWTQzR0Mrd2RXMlN5R0JtdzBobWhtbnAvQnc5Q01RWFlVTDUrdk5zcVJBK1NtdC8KbDdrUXhoeTdacG5SSWY2dVplMmQxQ0JPYjZRdWh4amsvci9YK29HQlo2cExMbHlWcjBUTTRCNzd3cWJ1cC9OVApPTkpXczVzRE1zSlRJRGxNcSt1emNIN0pLbUNQeEIvOW5lc0ZqY1JQd1FLR0hjLzlpVkh0YXIyQmdoSmNGalpOCmlrS005UjNldFdQY1FSRUxqTUtuZnUrNjduTDl6VmszVHNTTlNhMmJybGo1cXcrQm5Rc3F6U2JoUklUOU1mVVEKRnBJKzZDa0NnWUVBekgzb2lQeVJiMDJRbXB0am1RSm8zR2tBbkxmeHRjVHpDcXNDdkh4MGhMMkF3T0lKb3hwQwpoamFZMllvSVZtekZnM2dEaU51MWpIbG9JQStiSGpMLy95Ry9pRys4bTdORUdDZWNLd2h2ZG9PV1p5Lzh2ZWViCm1sbUJxVVFLeVJucEZDTFlrRGR4QzZ2OXVydGptaUNtNkF0VjZwQUlBSHBLYUs2L1JvMjMydk1DZ1lFQTNheEQKUEErcHdnNHZsSFA4ZXZUZlczVzNldUVmNnljVjBRRXIwcFdCN0Q0anZGL2FMWjk1R2N6MHpUTVdMZmdOU2w2Zgo5dGZ1M1ZUSXlzVllCcVBIcjcyMHVnL1ZXcG55RDdRMWdVVnU0TEJFTVVRVmMzMlR2MTlIbk9XaWlIa0VwZ25FCmtaTlhmSGlYcDY2Y28zNGxtOG0wOUg3OWNnbXNGTHFWTzdPdE54TUNnWUVBbVpkWU9NdTdVS1lwbm5abjhGem0KOWVYSUYrM3hGbDIvVHB2emlpN1FOWU5BV1o5dExaeGpxdnNIQXgyeDlYZnRRam02TGVrWUMxS0U2cy9ONm5qVAozb1V5bnYrTjRrUmJPT2xIV3VzVERTajRwcmhjVlNiSXNMM1pyWkQxcU9aVk1sS1o1bmc5NkU1ZVhRcXlYT2w1CmM0QlFIOFhldkwwZGRsTUtSNnZhRkJFQ2dZRUEyN0tVUEYybHVNK0lkcEJ4eG9jVks3ZENyc1dhZGR3WjhqZy8KNzRqLzZGMDUyOFFBSDhGeks1QUhlNnhMS2lvek9lY0lrWVEzbUNNa2tscitRQzVvaFpQMkg0WDd4YnpYdkpxMQpnTGFKQ3FXSUlHL0M5dUNaNDB5U1ZEei9WbFRpdDVEc3dmOE84UzB2MlIvazNPRDBjeTk1YWV6R1VoU2wrVEZuCklIR1dsZ01DZ1lCb244SFppNGNUYVJrRTVySHlHU3ZqVkhzeUhZZzhMSWZVbDdUYk5laDFkb0YrUHdxL0pGdEgKVW85NzVFSWVJblZ0dWxLcjNEL01yM25scmc3M1U3SC8xV1YrTnBWcWV3TWZJelBIVzUzekt1NWkyWG96RGxLbwpGb1lsak5EVlBXTk9RNi9mN05ubDNKd2ZlblR4U011c0N4a3JVcU9oeU5rMUV1Vm9wNDZVT1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
    - name: luweb@foxmail.com/cf1b8d269da816c6bf803b6591761eca
      user:
        auth-provider:
          config:
            client-id: kube
            client-secret: kube
            id-token: eyJraWQiOiIyMDIwMDQyNTE4MjkiLCJhbGciOiJSUzI1NiJ9.eyJpYW1faWQiOiJJQk1pZC0yNzAwMDM3NTdZIiwiaXNzIjoiaHR0cHM6Ly9pYW0uYmx1ZW1peC5uZXQvaWRlbnRpdHkiLCJzdWIiOiJsdXdlYkBmb3htYWlsLmNvbSIsImF1ZCI6Imt1YmUiLCJnaXZlbl9uYW1lIjoi5Lyf5b2sIiwiZmFtaWx5X25hbWUiOiLnvZciLCJuYW1lIjoi5Lyf5b2sIOe9lyIsImVtYWlsIjoibHV3ZWJAZm94bWFpbC5jb20iLCJleHAiOjE1ODk3MDI2ODcsInNjb3BlIjoiaWJtIG9wZW5pZCBjb250YWluZXJzLWt1YmVybmV0ZXMiLCJpYXQiOjE1ODk2OTkwODcsInN1Yl9jZjFiOGQyNjlkYTgxNmM2YmY4MDNiNjU5MTc2MWVjYSI6Imx1d2ViQGZveG1haWwuY29tIiwiaWFtX2lkX2NmMWI4ZDI2OWRhODE2YzZiZjgwM2I2NTkxNzYxZWNhIjoiSUJNaWQtMjcwMDAzNzU3WSIsInJlYWxtZWRfc3ViX2NmMWI4ZDI2OWRhODE2YzZiZjgwM2I2NTkxNzYxZWNhIjoiSUJNaWQtbHV3ZWJAZm94bWFpbC5jb20iLCJncm91cHNfY2YxYjhkMjY5ZGE4MTZjNmJmODAzYjY1OTE3NjFlY2EiOltdfQ.ckI1R1LzQPMIXpqDWlZc6ZoiL9xdNuQwHCgwslWJ-iHpwRF6sjCPThDeMjx6zKYFS6ZJrKDLqAymPKuTJq5yBY6IK7bRPDTzgvYg5FMhC9x0SbwpkmXTx9OGn_G7CBSX96z_C82GyD9JLrNbeL2Me2ins_v_nWlMzePCSb8I8hw-lTuvFuHNVgC18DlPCtHfdn7uWz6FfqHASewJ7z9jus5sJfNnTWe5dATijxSEvUEZmzovR7EPEBdEyrl3FCPD-ajhRhRuYdK1CBCMtl17EpI7l-xdsl_yjBSMECj_i3vYwHAKWhXdtZo88083HG73q3ndD5_saTb0RimFafEbww
            idp-issuer-url: https://iam.bluemix.net/identity
            refresh-token: OKAxSQC3ue2e-g8SG770DR_JLBfhjTpqjMIXcRa6YeJ7iyvmyx2o0rCeeuFNvGh7neOgHLAaFgPeVr76rZmtgDwXIGQHxodecVuqBQGfhgmpiLyJ4FtRfgg5QxurlRTks5WYiBP9L-55W5sxAFdoSkGFGfRPgJYw1tmovIoypvpF9i-AKBTppKVQgBEQZAZ6VCLOXWVuwXAoFvLNA0FNzGLFQwF4W72nqVXgd-ZoWhDFQXwaa1BqkZe2OqJq-xKVgy_NW_xrVMn225OhejeGZUuXpyXu_Hsc0_Dc_QBtoYReo6ZKIg5gp59lcGxP3WD25E5P037kpaIAc4VerVpb4W8LYk0MD7IE9hTsVXSwZBYoqyOW4UM0xsY5fxwHQgtKrGo69T2tGeHI8TZZ2Symni2ZnjnXkUF5rcv00arLsP8QvU9nDO_2Je7FxbTaDY41fw2homk_Pz5WACSaU4-CDp-QpWDuNMYYlGmZfp97eEbyPEOBfFuFtpHeQT2WnzazV59uBoePu-IBweCAWwOBc2us0KC9yfr6nmKr7hzFOsvuF63-b7Q5RplkW52uGhBtEUKYsHnvW0w8shci3Enb5HIfJEeI-rRH941xpstdBNK9hijKMcUUHStSicE3AjEOUbtHxFtK1Gw9bdAGBk2nYlaRv-kyC8hBqrz2qCyDgon7BVzV7beQ5LJu_umoUGn5NGhoaeRKEBh9D150apBkMXaGN3G70eXZsg1Mnj_N4RgRYxQXnI4JhV0Mbs92_KKTg3OiByKUA0d9XAgILwmwMvJvdFbh7TSGsiBFnTF3Jq9STBgWqR9wJHT8qhcNANDZqy36gKxV1bC69S4X56BdoFG5TtvpCfROjVNdhOdh-orprlXS-Insv07Rc1JktvL6D9xXlUlQvvIzmVSJEB8dEc6u-A6pgZkGHDWjZVaDk1zfdQBiAIX8ca_s7Scp_9ab2fkb71_5l3bPwwthCtaKZ4Gqsfj2Z9G1xzwIAk_fTque0xoujsf0SJgKS-Mb-262ZOw
          name: oidc
  ca-hou02-mycluster.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIFOzCCAyOgAwIBAgIUV0xh89ParPNmn3EN5HnALA3ztyMwDQYJKoZIhvcNAQEL
    BQAwLTErMCkGA1UEAwwiYnFydmk0YmQwMXJuNWttYzBmbGcta3ViZXJuZXRlcy1j
    YTAeFw0yMDA1MTAxMjUzNTJaFw00NzA5MjYxMjUzNTJaMC0xKzApBgNVBAMMImJx
    cnZpNGJkMDFybjVrbWMwZmxnLWt1YmVybmV0ZXMtY2EwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQD1kk3a08J5zOO+55WUTbmuJyki4WytHJJEFkH2zrrr
    NNoyHwP67YmlS6XXCNIzYGQFdzKAm2awfivc3QawHCwxKoCodrCSdJWZv+wrzOcm
    J6clIaNZIeiYM4Sgqt4GIrqUdFrt6IVZ8xKGsEmpma9Sdo7kRrVr4Abt9QnnAiex
    uYFkk/DNVLs/5cXcwxsjWlqONMOPLr87EOsV7NssKwlMzPk27yPaRoWoYFfi5zof
    cjoi2dKqYv27yAsTzrp5o5r2cp/LjwO4eLoiFDVJikfrv35fGiIiRf3qRbW/mkRd
    UaEZwXGhpzk1A5roQclDQ7O9xRPF6kRyzlsbVWJQbgV6BT1n41KjashASb9oQHlw
    U+RzVyv1v4A4EXi4Ml/nocdCEztuuYheC86xMoEMHcnlaqvQJ0qANx5PScK1Ah0x
    kNIB730IiPvBRcaMVFJqPHfnpyZUm5aedceqmKdIC+Tp13RX7IaNM2qmXYcIR6Xi
    xQj3HU9qcVqnHkZc0cUiAkTq3zFuzfbXVxDIPen1YitEEs9VQahhkncoK+Tuz68B
    CUS8n27JqpB/+hxHj6uaqFa8mcBjcpdaVX1VJnaM0f0WqVdrTlaU1YcynLp8GRSF
    QUhQ4a4dM5c2Mu6HCK3gpvAjn5niUB7GF2ICHXGDDW1x9f9MuDG1Q/OkChMI9f9s
    TwIDAQABo1MwUTAdBgNVHQ4EFgQU9affVxYXK2/l2BvbvtGXfSK6s5UwHwYDVR0j
    BBgwFoAU9affVxYXK2/l2BvbvtGXfSK6s5UwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEAMFxqsvHNyIORdWgjf0y/hqCDE5YKc3NyCuXSt0xIVzeb
    gKcq46DBO2TdJQ/zcFSJRpc8qVAVyIfelj2drQojfcvevVQx59pvIicP7vnYa/iA
    0p9AU7/o1WY5VOfDoJmnpZeDolC6qHVrGIPGltrLiXA4by6oXj6rsoqOtjww8CUo
    BO9bLZPZ1yggbtz9WXbYu1S78g07L9UVS3jcEidA8cJ8L1aZAnalFIk259PUwZrm
    UaIWrDKImaN5lrg7GBQz/1xcRoxwOHTVmDMUNTYffoM1Uyl6h4qjvJ+cicWHpisw
    vlPiVXv0AB+7i5mACn5sOTWzBFDfpPoknSPVDhCfMK3bULrfEiQdMVn7nTmAVL4/
    HhMmscPviQm0kUM+LV8S67YZFiMfn6XwzVreVAJ03EsymfHvsJLg9zZiM/GVQ4Bw
    0Inxhsg0sGyM3kufwRR/HvjKRki1MRNxfYGSCrx+ToFxZ/Z2inzhPEqfEPfFEcle
    tp1AHz+qT4i+sjClbTo9DTQs+ZTbvq0+eoAYrDhbqi/FZi0rrGGpvnA94STtERlE
    Et7X7GIgpkw88p7+O9lJGo/3wqoyIvF8kQGK+w1t4cBR+8Uup3CDbEjcjW52TGQt
    y9KIhYUE5uPLLkRhnrELp2/fB8J/NOE3ocW7ZRJlohTAHCMUiCwr4/dHOGXAOSM=
    -----END CERTIFICATE-----%
  feconfig.yaml: |-
    # fabric引擎端口
    BaasFabricEnginePort: 4991
    # baas 的根目录
    BaasRootPath: /data/baas/manager
    # nfs server ip
    # BaasNfsServer: docker.for.mac.host.internal
    BaasNfsServer: 118.89.37.37
    # k8s引擎地址
    BaasKubeEngine: http://localhost:5991
    # 在baas根目录下nfs共享目录
    BaasNfsShared: baas-nfsshared
    # 在baas根目录下fabric k8s模板目录
    BaasTemplate: baas-template
    # 保存chaincode的gopath下的src目录
    BaasChaincodeGithub: github.com/baaschaincodes
    # 共识排序参数
    OrdererBatchTimeout: 1s
    OrdererMaxMessageCount: 10
    OrdererAbsoluteMaxBytes: 99 MB
    OrdererPreferredMaxBytes: 512 KB

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baasmanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: baasmanager
      app.kubernetes.io/instance: 1.17.9
  template:
    metadata:
      labels:
        app.kubernetes.io/name: baasmanager
        app.kubernetes.io/instance: 1.17.9
    spec:
      containers:
        - name: gateway
          image: docker.io/luoweb/baasmanager:2.0
          imagePullPolicy: IfNotPresent
          command: ["/app/baas-gateway"]
          ports:
            - containerPort: 6991
              protocol: TCP
          volumeMounts:
            - name: baasmanager
              mountPath: "/app/gwconfig.yaml"
              subPath: gwconfig.yaml
            - name: baasmanager
              mountPath: "/etc/gateway/dbconfig.yaml"
              subPath: dbconfig.yaml
        - name: kubeengine
          image: docker.io/luoweb/baasmanager:2.0
          imagePullPolicy: IfNotPresent
          command: ["/app/baas-kubeengine"]
          ports:
            - containerPort: 5991
              protocol: TCP
          volumeMounts:
            - name: baasmanager
              mountPath: "/app/keconfig.yaml"
              subPath: keconfig.yaml
            - name: baasmanager
              mountPath: "/etc/k8sconfig/config"
              subPath: k8sconfig
            - name: baasmanager
              mountPath: "/etc/k8sconfig/ca-hou02-mycluster.pem"
              subPath: ca-hou02-mycluster.pem
        - name: fabricengine
          image: docker.io/luoweb/baasmanager:2.0
          imagePullPolicy: IfNotPresent
          command: ["/app/baas-fabricengine"]
          ports:
            - containerPort: 4991
              protocol: TCP
          volumeMounts:
            - name: baasmanager
              mountPath: "/app/feconfig.yaml"
              subPath: feconfig.yaml
            - name: nfs-client-root
              mountPath: "/data/baas/manager"
        - name: baas-frontend
          image: docker.io/luoweb/baasmanager:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4991
              protocol: TCP
          volumeMounts:
            - name: baasmanager
              mountPath: "/etc/nginx/conf.d/baas.conf"
              subPath: baas.conf
      volumes:
        - name: baasmanager
          configMap:
            name: baasmanager
        - name: nfs-client-root
          nfs:
            server: 118.89.37.37
            path: /data/baas/manager
          # nfs:
          #   server: docker.for.mac.host.internal
          #   # server: 192.168.3.31
          #   path: /System/Volumes/Data/opt/data/k8s
---
apiVersion: v1
kind: Service
metadata:
  name: baasmanager
  namespace: default
  labels:
    app.kubernetes.io/name: baasmanager
    app.kubernetes.io/instance: 1.17.9
spec:
  type: NodePort
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      nodePort: 32600
    - name: gateway-port
      port: 6991
      targetPort: 6991
      nodePort: 32601
    - name: kubeengine-port
      port: 5991
      targetPort: 5991
      nodePort: 32602
    - name: fabricengine-port
      port: 4991
      targetPort: 4991
      nodePort: 32603
  selector:
    app.kubernetes.io/name: baasmanager
    app.kubernetes.io/instance: 1.17.9
